# Generated by Django 3.1.1 on 2020-10-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='comment',
            new_name='comments',
        ),
    ]
