# Generated by Django 3.1.1 on 2020-10-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='bread',
            new_name='breed',
        ),
    ]
